---
- name: Configure BIND9 DNS
  hosts: dns_servers
  become: true

  tasks:
    - name: Install BIND9
      ansible.builtin.apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        state: present
        update_cache: true

    - name: Configure BIND9 Options
      ansible.builtin.copy:
        dest: /etc/bind/named.conf.options
        content: |
          options {
              directory "/var/cache/bind";
              recursion yes;
              allow-query { any; };
              forwarders {
                  8.8.8.8;
                  8.8.4.4;
              };
              dnssec-validation auto;
              listen-on-v6 { any; };
          };
        owner: root
        group: bind
        mode: "0644"
      notify: Restart BIND9

    - name: Configure Local Zone Declaration
      ansible.builtin.copy:
        dest: /etc/bind/named.conf.local
        content: |
          zone "lab" {
              type master;
              file "/etc/bind/db.lab";
          };
        owner: root
        group: bind
        mode: "0644"
      notify: Restart BIND9

    - name: Create lab Zone File
      ansible.builtin.copy:
        dest: /var/lib/bind/db.lab
        content: |
          $TTL    604800
          @       IN      SOA     dns.lab. admin.lab. (
                                        3         ; Serial
                                   604800         ; Refresh
                                    86400         ; Retry
                                  2419200         ; Expire
                                   604800 )       ; Negative Cache TTL
          ;
          @       IN      NS      dns.lab.
          dns     IN      A       192.168.2.10
        owner: bind
        group: bind
        mode: "0644"
      notify: Restart BIND9

    - name: Create TSIG key for Dynamic Updates
      ansible.builtin.copy:
        dest: /etc/bind/tsig.key
        content: |
          key "tsig-key" {
              algorithm hmac-sha256;
              secret "{{ vault_tsig_key_secret }}";
          };
        owner: root
        group: bind
        mode: "0640"

    - name: Configure Local Zone Declaration
      ansible.builtin.copy:
        dest: /etc/bind/named.conf.local
        content: |
          include "/etc/bind/tsig.key";
          zone "lab" {
              type master;
              allow-update { key "tsig-key"; };
              file "/var/lib/bind/db.lab";
          };
        owner: root
        group: bind
        mode: "0644"
      notify: Restart BIND9

  handlers:
    - name: Restart BIND9
      ansible.builtin.service:
        name: bind9
        state: restarted
